### ISSUE TITLE
Choose a logo for our organization

### ISSUE THREAD

**Issue by mohamadsabra** [Performa2018/PerformaBeta#1]
Dear @rkhawand,

Kindly we need to chose a convenient logo for our organization.

We will share some examples in the comments.

Best Regards,

**Comment by rkhawand** [comment]
Dear @mohamadsabra 

Please check the logo that I
![performa2018_1](https://user-images.githubusercontent.com/33514574/34413476-7a655608-ebec-11e7-9b1d-8fad0a82b187.JPG)
 uploaded 

Regards

**Comment by mohamadsabra** [comment]
Dear @rkhawand,

Kindly check the below logo and if it's possible to add the name in it.

![epic-circular-logo-creator-36-on-free-logo-templates-with-circular-logo-creator](https://user-images.githubusercontent.com/34799714/34413556-e40e09ce-ebec-11e7-9173-8cf4100c27be.jpg)

Best Regards,

**Comment by rkhawand** [comment]
![performalogo](https://user-images.githubusercontent.com/33514574/34414000-740546d0-ebef-11e7-9ce2-e519e3943aae.jpg)
